#!/usr/bin/env python3
from pathlib import Path
import subprocess, socket

logo = """
           _                     _           _      _
          (_)                   | |         | |    (_)
 _ __ ___  _ _ __ _ __ ___  _ __| |__  _   _| |__   _  ___
| '_ ` _ \| | '__| '__/ _ \| '__| '_ \| | | | '_ \ | |/ _ \
| | | | | | | |  | | | (_) | |  | | | | |_| | |_) || | (_) |
|_| |_| |_|_|_|  |_|  \___/|_|  |_| |_|\__,_|_.__(_)_|\___/
============================================================
"""
print(logo)

if not Path("/srv/internals/dhparam.pem").is_file():
  print('[nginx] Did not found dhparams, generating. This may take a while..')
  subprocess.run('openssl dhparam -out /srv/internals/dhparam.pem 2048', stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT, shell=True)
  print('[nginx] Finished generating.')
else:
  print('[nginx] Using existing dhparams')

hostname = socket.gethostname()
#subprocess.run('letsencrypt certonly -a webroot --webroot-path=/tmp/letsencrypt --rsa-key-size 4096 -d %s' % hostname, shell=True)

print('[nginx] Using %s as hostname' % hostname)

print('[mirror] Ready to serve!')
subprocess.run('/usr/bin/supervisord', stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
